---
pitch: 0 #+/- semitones, 12 for every octave
voices:
    af_heart: 0.5
    jf_alpha: 0.5
speed: 1.0 # min 0.5 max 2.0
index_rate: 1 # Search feature ratio (controls accent strength, too high has artifacting)
filter_radius: 3 # If >=3: apply median filtering to the harvested pitch results. The value represents the filter radius and can reduce breathiness
protect: 0.33 # Protect voiceless consonants and breath sounds to prevent artifacts such as tearing in electronic music. Set to 0.5 to disable. Decrease the value to increase protection, but it may reduce indexing accuracy